name: Deploy
on:
  push:
    branches:
      - main
jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        # node version
      - name: Use Node.js 17.x
        uses: actions/setup-node@v1
        with:
          node-version: 17.x
        # caching
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-deploy-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            cache-${{ runner.os }}-deploy-${{ env.cache-name }}-
            cache-${{ runner.os }}-deploy-
            cache-${{ runner.os }}-
        # install dependencies
      - name: Install dependencies
        run: npm install
        # run tests
      - name: Test
        run: npm test
        env:
          CI: true
        # create tag
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
        # create release
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
